### ISSUE TITLE
Allow Surrogate Table Lookup from floating point columns

### ISSUE THREAD

**Issue by gillins** [ubarsc/tuiview#21]
Currently, only integer columns have the "Set column as Color Table Lookup" menu option. As @petescarth discovered this is a bit of a pain if you get `pyshepseg` to calculate a mean value for a segment as it saves this in a float column (although note that median values get saved in an int column). You have to create a new column with the integer version of the mean value.

I don't think there is any harm in allowing a Colour Table lookup on float columns by doing a `round()` first? Any thoughts @shepjd?

**Comment by shepjd** [comment]
Hi Sam

Go for it, makes perfect sense to me.

Cheers
James
________________________________
From: Sam Gillingham ***@***.***>
Sent: Sunday, September 19, 2021 3:55 PM
To: ubarsc/tuiview ***@***.***>
Cc: James Shepherd ***@***.***>; Mention ***@***.***>
Subject: [ubarsc/tuiview] Allow Surrogate Table Lookup from floating point columns (#21)


Currently, only integer columns have the "Set column as Color Table Lookup" menu option. As @petescarth<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpetescarth&data=04%7C01%7Cshepherdj%40landcareresearch.co.nz%7C0aa07eb3dfe04d219bca08d97b215602%7C43050530b3c74cd2a11cb826b2604b5b%7C0%7C0%7C637676205382894500%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=24GhHDpvYYRpZiNDQdBaCpRuXKWhxsiQuXgochpiCEE%3D&reserved=0> discovered this is a bit of a pain if you get pyshepseg to calculate a mean value for a segment as it saves this in a float column (although note that median values get saved in an int column). You have to create a new column with the integer version of the mean value.

I don't think there is any harm in allowing a Colour Table lookup on float columns by doing a round() first? Any thoughts @shepjd<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fshepjd&data=04%7C01%7Cshepherdj%40landcareresearch.co.nz%7C0aa07eb3dfe04d219bca08d97b215602%7C43050530b3c74cd2a11cb826b2604b5b%7C0%7C0%7C637676205382899474%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lpqJrWV5Bx8FaP5LuAdH0xjJ3jFbuNtgi2EsK4HtUCc%3D&reserved=0>?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fubarsc%2Ftuiview%2Fissues%2F21&data=04%7C01%7Cshepherdj%40landcareresearch.co.nz%7C0aa07eb3dfe04d219bca08d97b215602%7C43050530b3c74cd2a11cb826b2604b5b%7C0%7C0%7C637676205382904454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=jbqHrVB%2FZI0RktHUYArFZGY%2Bm6Evx%2BhSN90XOISXwvM%3D&reserved=0>, or unsubscribe<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUQY3GHQ6ZK6XWG324FVBBDUCVNLBANCNFSM5EJ4KVWA&data=04%7C01%7Cshepherdj%40landcareresearch.co.nz%7C0aa07eb3dfe04d219bca08d97b215602%7C43050530b3c74cd2a11cb826b2604b5b%7C0%7C0%7C637676205382904454%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ya1xRml8oahYRH5VbL2SjQljgc3sgjjHkPManNgw82c%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cshepherdj%40landcareresearch.co.nz%7C0aa07eb3dfe04d219bca08d97b215602%7C43050530b3c74cd2a11cb826b2604b5b%7C0%7C0%7C637676205382909432%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CzxCiGJY3orzJsAxfN2gGbe2mL4DY0NPEPqXy4AznzE%3D&reserved=0> or Android<https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cshepherdj%40landcareresearch.co.nz%7C0aa07eb3dfe04d219bca08d97b215602%7C43050530b3c74cd2a11cb826b2604b5b%7C0%7C0%7C637676205382914408%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zd2imkfnvzkWuMdPnwiFsKIlRLIvkFsDNcHoNupwJRE%3D&reserved=0>.

________________________________

Please consider the environment before printing this email
Warning: This electronic message together with any attachments is confidential. If you receive it in error: (i) you must not read, use, disclose, copy or retain it; (ii) please contact the sender immediately by reply email and then delete the emails.
The views expressed in this email may not be those of Landcare Research New Zealand Limited. http://www.landcareresearch.co.nz
