### ISSUE TITLE
ImportError: cannot import name 'vectorrasterizer' from 'tuiview'

### ISSUE THREAD

**Issue by zhangch-ss** [ubarsc/tuiview#29]
Hi, in viewerlayers.py, there is an error in "from . import vectorrasterizer", I guess the vectorrasterizer.py file is missing. But I only found that there is a vectorrasterizer.c file, are the two related? I am running tuiview under Windows Pycharm.

**Comment by gillins** [comment]
Yes the `vectorrasterizer` module is created from `vectorrasterizer.c` as part of the installation process. I am guessing you haven't run `python setup.py install` to build and install?
I would note getting all this to work on Windows is very hard unless you are familiar with the Microsoft C++ Compiler. First you will need the appropriate version of MSVC for the Python you are using (see https://wiki.python.org/moin/WindowsCompilers). Secondly you will need to run `vcvars.bat` or whatever it is called these days to setup the environment for MSVC before running `setup.py` and set the `GDAL_ROOT` environment variable to the location of your `gdal` installation. 

I would strongly recommend using conda-forge (https://conda-forge.org/) to install TuiView on Windows since this is all handled for you. All the required dependencies are also installed. 

Compiling from source is much easier on Linux since the appropriate C/C++ compilers are installed (or very easy to obtain).

**Comment by zhangch-ss** [comment]
Thanks for your reply, I will try it

**Comment by zhangch-ss** [comment]
> Yes the `vectorrasterizer` module is created from `vectorrasterizer.c` as part of the installation process. I am guessing you haven't run `python setup.py install` to build and install? I would note getting all this to work on Windows is very hard unless you are familiar with the Microsoft C++ Compiler. First you will need the appropriate version of MSVC for the Python you are using (see https://wiki.python.org/moin/WindowsCompilers). Secondly you will need to run `vcvars.bat` or whatever it is called these days to setup the environment for MSVC before running `setup.py` and set the `GDAL_ROOT` environment variable to the location of your `gdal` installation.
> 
> I would strongly recommend using conda-forge (https://conda-forge.org/) to install TuiView on Windows since this is all handled for you. All the required dependencies are also installed.
> 
> Compiling from source is much easier on Linux since the appropriate C/C++ compilers are installed (or very easy to obtain).

Thanks for your reply, I will try it

**Comment by zhangch-ss** [comment]
Thanks for your help, I successfully solved this problem using your suggestion
